Updated translations and added a new file. I could't compile them since there seems to be a problem in debian::template in italian and english directories:
/webwml/italian/devel/debian-med$ make install
cd ../../../english/template/debian && sed -e '/^#/d' -e '/^<perl>/,/^<\/perl>/!d' language_names.wml  | eperl -B '<perl>' -E '</perl>' - >/dev/null
wml -q -D CUR_YEAR=2002 -o UNDEFuIT:dental.it.html@g+w   dental.wml
ePerl:Error: Perl parsing error (interpreter rc=255)

---- Contents of STDERR channel: ---------
syntax error at /tmp/wml.13978.tmp1.wml line 1001, near "breton"
Execution of /tmp/wml.13978.tmp1.wml aborted due to compilation errors.
------------------------------------------
** WML:Break: Error in Pass 3 (rc=74).
make: *** [dental.it.html] Error 1

CVS version numbers

italian/devel/debian-med/his.wml: INITIAL -> 1.1 
italian/devel/debian-med/index.wml: 1.2 -> 1.3 
italian/devel/debian-med/research.wml: 1.1 -> 1.2